version: '3.7'

services:
  ml_train_service:
    build: ./ml_train_service
    volumes:
      - ./ml_train_service/:/app/
    env_file:
      - .env
    ports:
      - 8001:8000

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ml_train_service


