version: '3.7'

services:
  ml_train_service:
    build: ./ml_train_service
    volumes:
      - ./ml_train_service/:/app/
    env_file:
      - .env
    ports:
      - 8001:8000

  mps_training_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_mps_training:/var/lib/postgresql/data/
    env_file:
      - .env

  mps_pgadmin:
    container_name: mps_pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - mps_training_db
    volumes:
      - pgadmin:/root/.pgadmin


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ml_train_service

volumes:
  postgres_data_mps_training:
  pgadmin:


